services:
  - type: web
    name: kosge-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
    rootDir: backend
    autoDeploy: true

  - type: web
    name: kosge-frontend
    env: static
    buildCommand: ""
    staticPublishPath: public
    rootDir: frontend
    autoDeploy: true
